SRCREV_pn-linux-dfe ?= "${AUTOREV}"
SRC_URI_pn-linux-dfe ?= "git://git.am.freescale.net/gitolite/users/b34330/linux.git;protocol=git;branch=sdk_dfe_dev"

SRCREV_pn-rrh-utils ?= "${AUTOREV}"
SRC_URI_pn-rrh-utils ?= "git://git.am.freescale.net/gitolite/users/b34330/rrh_utils.git;protocol=git;branch=sdk_dfe_dev"


#SRC_URI_pn-rrh-utils ?= "git:///home/r39151/dfe/rrh_utils.no_lua_hdrs;protocol=file;branch=sdk_dfe_dev"

SRCREV_pn-u-boot-dfe ?= "${AUTOREV}"
SRC_URI_pn-u-boot-dfe ?= "git://git.am.freescale.net/gitolite/users/b34330/u-boot.git;protocol=git;branch=sdk_dfe_dev"
